version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
      - run: 
          name: Install NPM packages
          command: npm install
      - run:
          name: Lint files
          command: npm run lint
      - run:
          name: Prettier files
          command: npm run format
      # - run:
      #     name: Jest tests
      #     command: npm run jest
      - run:
          name: Build
          command: npm run build
      # - run:
      #     name: Deploy
      #     command: npx netlify-cli deploy --site "$NETLIFY_API_ID" --auth "$NETLIFY_ACCESS_TOKEN" --prod

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - circleci-project-setup
    jobs:
      - build
                